site_name: The nnetsauce
theme:
  name: cyborg
  nav_style: dark
  #name: null
  #custom_dir: 'custom_theme/'

docs_dir: sources
repo_url: https://github.com/Techtonique/nnetsauce
edit_uri: ""
site_description: 'Documentation for the nnetsauce.'

nav:
    - Quickstart examples:
      - Classification: examples/classification.md
      - Regression: examples/regression.md
      - Time series: examples/time_series_examples.md
    - Documentation:
      - Classifiers: documentation/classifiers.md
      - Regressors: documentation/regressors.md
      - Time series: documentation/time_series.md
    - Contributing Guide: CONTRIBUTING.md  
    - License: LICENSE.md
      
        