site_name: Techtonique/nnetsauce
theme:
  name: darkly # sandstone # slate # lux # darkly
  nav_style: dark
  #name: null
  #custom_dir: 'custom_theme/'

google_analytics: ['UA-146345113-2', 'https://techtonique.github.io/nnetsauce/']

docs_dir: sources
repo_url: https://github.com/Techtonique/nnetsauce
edit_uri: ""
site_description: 'Documentation for the nnetsauce.'

nav:
    - Quickstart examples:
      - Classification: examples/classification.md
      - Regression: examples/regression.md
      - Time series: examples/time_series_examples.md
    - Documentation:
      - Classifiers: documentation/classifiers.md
      - Regressors: documentation/regressors.md
      - Time series: documentation/time_series.md
      - Scoring metrics: documentation/scoring_metrics.md
    - Contributing: CONTRIBUTING.md  
    - License: LICENSE.md
    - References: REFERENCES.md
    - Techtonique: ../
      
        